### ISSUE TITLE
Easy way to start httpster once loaded locally....

### ISSUE THREAD

**Issue by dinooz** [SimbCo/httpster#25]
I create a simple HelloWorld app with npm init....

{
  "name": "hw",
  "version": "0.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Dinooz <bernardino.lopez@gmail.com> (http://www.dinooz.com
/)",
  "license": "ISC",
  "dependencies": {
    "httpster": "^1.0.1"
  }
}

Later in windows try to install locally httpster... npm install httpster --save... it added to package.json file... then in order to run it..have to put the full path...

I wonder if there is a way to create a link from the root of the app to run easily .... 

c:\nodejs\hw>node c:\nodejs\hw\node_modules\httpster\bin\httpster
Starting HTTPster v1.0.1 on port 3333 from c:\nodejs\hw
^C
c:\nodejs\hw>node node_modules\httpster\bin\httpster
Starting HTTPster v1.0.1 on port 3333 from c:\nodejs\hw

**Comment by db6edr** [comment]
Add the following to the `scripts` section of your package.json:
```javascript
"start" : "node_modules/.bin/httpster"
```
then run `npm start` and you should be fine.
