### ISSUE TITLE
Run httpster with pm2

### ISSUE THREAD

**Issue by rodrigocnascimento** [SimbCo/httpster#31]
Hi, there`s a way to run httpster with pm2? My application keeps falling, so I need to every time login into my server and start again. It's only for tests purpose but it's little anoying. 

Thank you for your time.

**Comment by simb** [comment]
Currently there is not a way to do this.  We are really just wrapping the static hosting from express to make things simpler.  If you you need to run it as a service you might be better served just writing the few lines of express to create your own server.  Then you can use pm2 as you would expect.

If you think this is something that would be really important to httpster users please feel free to reopen this ticket and we can discuss it further.
