### ISSUE TITLE
implement inline help

### ISSUE THREAD

**Issue by NathanStrutz** [SimbCo/httpster#33]
I'd hoped to find a `/?` or `-?` or `-h` or `--help` switch, but instead I just had to find the git repo and go over the readme again. I'd love it if one or all of these switches worked and told me what my command line options were (as it was, I wanted `-d`).

Funny enough, I didn't know you were the author. Thanks for a great tool, Simeon!

**Comment by simb** [comment]
That's a great suggestion.  I kinda thought we had done that.  We can look at adding an enhancement.

**Comment by simb** [comment]
@NathanStrutz I just went and looked and we do have a `-h` switch.  the current output is
```
  Usage: server [options]

  Options:

    -V, --version      output the version number
    -p, --port <port>  Port for server to run on - defaults to 3333
    -d, --dir [path]   Server directory - defaults to ./
    -z, --compress     Add support for compression
    -s, --pushstate    Add support for HTML5 pushstate
    -e, --env          Add support for setting environmental variables from .env file
    -b, --basic_auth   Add support for basic auth security. Uses environmental variables HTTPSTER_AUTH_USER and HTTPSTER_AUTH_PASS to authenticate
    -c, --cors         Add cors support
    -h, --help         output usage information
```

Are you looking for more than that?  Is something missing?

**Comment by NathanStrutz** [comment]
Oh man, I don't know how I missed that. Sorry and thanks!
